# Generated by Django 3.2.8 on 2022-11-16 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyaddress',
            name='address_type',
            field=models.CharField(blank=True, choices=[('B', 'Billing Adress'), ('O', 'Office Address')], default='B', max_length=20, null=True),
        ),
    ]
