# Generated by Django 3.2.8 on 2022-11-30 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_companyaddress_address_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basics_id', models.IntegerField()),
                ('percentile', models.FloatField(blank=True, null=True)),
                ('run_date', models.DateTimeField(blank=True, null=True)),
                ('violation_threshold', models.FloatField(blank=True, null=True)),
                ('exceeded_fmcsa_intervention_threshold', models.FloatField(blank=True, null=True)),
                ('measure_value', models.FloatField(blank=True, null=True)),
                ('on_road_performance_threshold_violation_indicator', models.CharField(blank=True, max_length=100, null=True)),
                ('serious_violation_investigation_past_12month_Indicator', models.CharField(blank=True, max_length=100, null=True)),
                ('total_inspection_with_violation', models.IntegerField(blank=True, null=True)),
                ('total_violation', models.IntegerField(blank=True, null=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='basics', to='company.company')),
            ],
        ),
        migrations.CreateModel(
            name='OperationClasfication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operaton_classfication_id', models.IntegerField(unique=True)),
                ('operation_classification_description', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LicensingAndInsurence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='insurance', to='company.company')),
            ],
        ),
        migrations.CreateModel(
            name='CargoCarried',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
        migrations.CreateModel(
            name='BasicsEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('code_mcmis', models.CharField(blank=True, max_length=100, null=True)),
                ('long_description', models.CharField(blank=True, max_length=100, null=True)),
                ('short_description', models.CharField(blank=True, max_length=100, null=True)),
                ('basics', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='basics_entity', to='company.basics')),
            ],
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('V', 'VEHICLE'), ('D', 'DRIVER'), ('H', 'HAZMAT')], max_length=20)),
                ('country', models.CharField(choices=[('U', 'USA'), ('C', 'CANADA')], max_length=20)),
                ('Inspections', models.IntegerField(blank=True, null=True)),
                ('oos', models.IntegerField(blank=True, null=True)),
                ('oos_percent', models.FloatField(blank=True, null=True)),
                ('national_average', models.FloatField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection', to='company.company')),
            ],
            options={
                'unique_together': {('type', 'company')},
            },
        ),
    ]
