# Generated by Django 3.2.8 on 2022-12-01 08:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_company_dba'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationclasfication',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company'),
            preserve_default=False,
        ),
    ]
