# Generated by Django 3.2.8 on 2022-12-01 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_operationclasfication_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basics',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basics', to='company.company'),
        ),
    ]
