# Generated by Django 3.2.8 on 2022-12-01 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_alter_basics_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyrepresentative',
            name='zip_code',
            field=models.CharField(max_length=10, verbose_name='Zip / Postal Code'),
        ),
    ]
