# Generated by Django 3.2.8 on 2022-12-01 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_alter_companyrepresentative_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyaddress',
            name='zip_code',
            field=models.CharField(max_length=10, verbose_name='Zip / Postal Code'),
        ),
    ]
