# Generated by Django 3.2.8 on 2022-12-01 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_alter_companyaddress_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationclasfication',
            name='operaton_classfication_id',
            field=models.IntegerField(),
        ),
    ]
