# Generated by Django 3.2.8 on 2022-12-02 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_alter_operationclasfication_operaton_classfication_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargocarried',
            name='cargo',
        ),
        migrations.AddField(
            model_name='cargocarried',
            name='cargo_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cargocarried',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='country',
            field=models.CharField(blank=True, choices=[('U', 'USA'), ('C', 'CANADA')], max_length=20, null=True),
        ),
    ]
