# Generated by Django 3.2.8 on 2022-12-29 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0017_alter_operationclasfication_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyaddress',
            name='street',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Street'),
        ),
    ]
