# Generated by Django 3.2.8 on 2022-12-29 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0018_companyaddress_street'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyaddress',
            name='total_driver',
        ),
        migrations.AddField(
            model_name='company',
            name='carrier_operation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='census_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='common_authority_status',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='contract_authority_status',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='ein',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='total_driver',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='licensingandinsurence',
            name='bipdInsuranceOnFile',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='licensingandinsurence',
            name='bipdInsuranceRequired',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='licensingandinsurence',
            name='bipdRequiredAmount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='licensingandinsurence',
            name='bondInsuranceOnFile',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='licensingandinsurence',
            name='bondInsuranceRequired',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
