# Generated by Django 3.2.8 on 2022-12-29 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0019_auto_20221229_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='docket_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
