# Generated by Django 3.2.8 on 2023-01-05 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0021_insurancehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurancehistory',
            name='effective_date_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='insurancehistory',
            name='effective_date_to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
