# Generated by Django 3.2.8 on 2023-01-05 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0022_auto_20230105_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurancehistory',
            name='coverage_from',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='insurancehistory',
            name='coverage_to',
            field=models.CharField(max_length=10),
        ),
    ]
