# Generated by Django 3.2.8 on 2023-01-06 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0023_auto_20230105_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurancehistory',
            name='policy_surety',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
