# Generated by Django 3.2.8 on 2023-01-06 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0024_alter_insurancehistory_policy_surety'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancehistory',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
