# Generated by Django 3.2.8 on 2023-01-09 07:49

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0025_insurancehistory_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyaddress',
            name='phone',
        ),
        migrations.AddField(
            model_name='company',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Phone Number'),
        ),
    ]
