# Generated by Django 3.2.8 on 2023-01-09 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0026_auto_20230109_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
