# Generated by Django 3.2.8 on 2023-01-09 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0027_alter_company_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carsh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crash_total', models.IntegerField()),
                ('fatal_crash', models.IntegerField()),
                ('injury_crash', models.IntegerField()),
                ('towaway_crash', models.IntegerField()),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='crashes', to='company.company')),
            ],
        ),
    ]
