# Generated by Django 3.2.8 on 2023-01-09 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0028_carsh'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Carsh',
            new_name='Crash',
        ),
    ]
